// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwqbaojpzrcyklziotwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cWJhb2pwenJjeWtsemlvdHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODM4MDQsImV4cCI6MjA1OTQ1OTgwNH0.ACYnQ_E8QoLfZY9_9hn4RYShJpELVzflVcUaQOrzrb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);