// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import {
	SUPABASE_URL,
	SUPABASE_ANON_KEY,
} from "@/utils/env";
import type { Database } from "./types";

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
	console.error(
		"Supabase URL or Anon Key is missing. Please check your environment variables.",
	);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
	SUPABASE_URL,
	SUPABASE_ANON_KEY,
);

/**
 * Get the storage URL for a bucket and file path
 * @param bucket - The storage bucket name
 * @param filePath - The path to the file within the bucket
 * @returns The complete URL to the file
 */
export const getStorageUrl = (
	bucket: string,
	filePath: string,
): string => {
	return `${SUPABASE_URL}/storage/v1/object/public/${bucket}/${filePath}`;
};

export default supabase;
